In [1]:
import pandas as pd
import numpy as np

In [2]:
file_path =  r"C:\\Users\\acer\\OneDrive\\Documents\\customer-lifetime-value-cohort-analytics\\Data\\olist_customers_dataset.csv"

df_customers = pd.read_csv(file_path)

df_customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [4]:
file_path =  r"C:\\Users\\acer\\OneDrive\\Documents\\customer-lifetime-value-cohort-analytics\\Data\\olist_orders_dataset.csv"

df_orders = pd.read_csv(file_path)

df_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [5]:
df_orders["customer_id"].nunique(), df_customers["customer_id"].nunique()

(99441, 99441)

In [6]:
df_orders_customers = df_orders.merge(
    df_customers,
    on="customer_id",
    how="inner"
)

df_orders_customers.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP

In [7]:
file_path = r"C:\\Users\\acer\\OneDrive\\Documents\\customer-lifetime-value-cohort-analytics\\Data\\olist_order_payments_dataset.csv"

df_payments = pd.read_csv(file_path)

df_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [8]:
df_clv = df_orders_customers.merge(
    df_payments,
    on="order_id",
    how="inner"
)

df_clv.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,payment_sequential,payment_type,payment_installments,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1,credit_card,1,18.12
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,3,voucher,1,2.00
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,2,voucher,1,18.59
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1,boleto,1,141.46
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1,credit_card,3,179.12

In [9]:
df_order_revenue = df_clv.groupby("order_id", as_index=False)["payment_value"].sum()

df_order_revenue.head()

                           order_id  payment_value
0  00010242fe8c5a6d1ba2dd792cb16214          72.19
1  00018f77f2f0320c557190d7a144bdd3         259.83
2  000229ec398224ef6ca0657da4fc703e         216.87
3  00024acbcdf0a6daa1e931b038114c75          25.78
4  00042b26cf59d7ce69dfabb4e55b4fd9         218.04

In [10]:
df_orders_revenue = df_orders_customers.merge(
    df_order_revenue,
    on="order_id",
    how="inner"
)

df_orders_revenue.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,38.71
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,141.46
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,179.12
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,72.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,28.62

In [11]:
df_customer_clv = df_orders_revenue.groupby("customer_unique_id").agg(
    total_revenue=("payment_value", "sum"),
    total_orders=("order_id", "nunique"),
    first_purchase=("order_purchase_timestamp", "min"),
    last_purchase=("order_purchase_timestamp", "max")
).reset_index()

df_customer_clv.head()

,customer_unique_id,total_revenue,total_orders,first_purchase,last_purchase
0,0000366f3b9a7992bf8c76cfdf3221e2,141.90,1,2018-05-10 10:56:27,2018-05-10 10:56:27
1,0000b849f77a49e4a4ce2b2a4ca5be3f,27.19,1,2018-05-07 11:11:27,2018-05-07 11:11:27
2,0000f46a3911fa3c0805444483337064,86.22,1,2017-03-10 21:05:03,2017-03-10 21:05:03
3,0000f6ccb0745a6a4b88665a16c9f078,43.62,1,2017-10-12 20:29:41,2017-10-12 20:29:41
4,0004aac84e0df4da2b147fca70cf8255,196.89,1,2017-11-14 19:45:42,2017-11-14 19:45:42

In [12]:
df_orders_revenue.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
payment_value                       0
dtype: int64

In [14]:
df_orders_revenue["payment_value"].describe()

count    99440.000000
mean       160.990267
std        221.951257
min          0.000000
25%         62.010000
50%        105.290000
75%        176.970000
max      13664.080000
Name: payment_value, dtype: float64

In [15]:
df_orders_revenue_clean = df_orders_revenue[df_orders_revenue["payment_value"] > 0]

In [16]:
df_orders_revenue_clean["payment_value"].describe()

count    99437.000000
mean       160.995124
std        221.952843
min          9.590000
25%         62.010000
50%        105.290000
75%        176.970000
max      13664.080000
Name: payment_value, dtype: float64

In [17]:
df_customer_clv_final = df_orders_revenue_clean.groupby("customer_unique_id").agg(
    total_revenue=("payment_value", "sum"),
    total_orders=("order_id", "nunique"),
    first_purchase=("order_purchase_timestamp", "min"),
    last_purchase=("order_purchase_timestamp", "max")
).reset_index()

df_customer_clv_final.head()

,customer_unique_id,total_revenue,total_orders,first_purchase,last_purchase
0,0000366f3b9a7992bf8c76cfdf3221e2,141.90,1,2018-05-10 10:56:27,2018-05-10 10:56:27
1,0000b849f77a49e4a4ce2b2a4ca5be3f,27.19,1,2018-05-07 11:11:27,2018-05-07 11:11:27
2,0000f46a3911fa3c0805444483337064,86.22,1,2017-03-10 21:05:03,2017-03-10 21:05:03
3,0000f6ccb0745a6a4b88665a16c9f078,43.62,1,2017-10-12 20:29:41,2017-10-12 20:29:41
4,0004aac84e0df4da2b147fca70cf8255,196.89,1,2017-11-14 19:45:42,2017-11-14 19:45:42

In [18]:
df_customer_clv_final["first_purchase"] = pd.to_datetime(df_customer_clv_final["first_purchase"])
df_customer_clv_final["last_purchase"] = pd.to_datetime(df_customer_clv_final["last_purchase"])

In [19]:
df_customer_clv_final["cohort_month"] = df_customer_clv_final["first_purchase"].dt.to_period("M")
df_customer_clv_final.head()

,customer_unique_id,total_revenue,total_orders,first_purchase,last_purchase,cohort_month
0,0000366f3b9a7992bf8c76cfdf3221e2,141.90,1,2018-05-10 10:56:27,2018-05-10 10:56:27,2018-05
1,0000b849f77a49e4a4ce2b2a4ca5be3f,27.19,1,2018-05-07 11:11:27,2018-05-07 11:11:27,2018-05
2,0000f46a3911fa3c0805444483337064,86.22,1,2017-03-10 21:05:03,2017-03-10 21:05:03,2017-03
3,0000f6ccb0745a6a4b88665a16c9f078,43.62,1,2017-10-12 20:29:41,2017-10-12 20:29:41,2017-10
4,0004aac84e0df4da2b147fca70cf8255,196.89,1,2017-11-14 19:45:42,2017-11-14 19:45:42,2017-11

In [20]:
df_cohort = df_orders_revenue_clean.merge(
    df_customer_clv_final[["customer_unique_id", "cohort_month"]],
    on="customer_unique_id",
    how="inner"
)

df_cohort.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,payment_value,cohort_month
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,38.71,2017-09
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,141.46,2018-07
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,179.12,2018-08
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,72.20,2017-11
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,28.62,2018-02

In [22]:
df_cohort["order_purchase_timestamp"] = pd.to_datetime(df_cohort["order_purchase_timestamp"])

In [23]:
df_cohort["order_month"] = df_cohort["order_purchase_timestamp"].dt.to_period("M")
df_cohort.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,payment_value,cohort_month,order_month
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,38.71,2017-09,2017-10
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,141.46,2018-07,2018-07
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,179.12,2018-08,2018-08
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,72.20,2017-11,2017-11
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,28.62,2018-02,2018-02

In [24]:
df_cohort["cohort_index"] = (
    (df_cohort["order_month"] - df_cohort["cohort_month"]).apply(lambda x: x.n)
)

df_cohort.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,payment_value,cohort_month,order_month,cohort_index
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,38.71,2017-09,2017-10,1
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,141.46,2018-07,2018-07,0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,179.12,2018-08,2018-08,0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,72.20,2017-11,2017-11,0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,28.62,2018-02,2018-02,0

In [25]:
cohort_pivot = df_cohort.pivot_table(
    index="cohort_month",
    columns="cohort_index",
    values="customer_unique_id",
    aggfunc="nunique"
)

In [26]:
cohort_pivot

cohort_index,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19,20
cohort_month,,,,,,,,,,,,,,,,,,,,
2016-09,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-10,321.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,1.0,NaN,1.0,2.0,2.0
2016-12,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01,764.0,3.0,2.0,1.0,3.0,1.0,4.0,1.0,1.0,NaN,3.0,1.0,6.0,3.0,1.0,1.0,2.0,3.0,1.0,NaN
2017-02,1752.0,4.0,5.0,2.0,7.0,2.0,4.0,3.0,3.0,4.0,2.0,5.0,3.0,3.0,2.0,1.0,1.0,4.0,NaN,NaN
2017-03,2636.0,13.0,10.0,10.0,9.0,4.0,4.0,8.0,9.0,2.0,10.0,4.0,6.0,3.0,4.0,6.0,2.0,4.0,NaN,NaN
2017-04,2352.0,14.0,5.0,4.0,8.0,6.0,8.0,7.0,7.0,4.0,6.0,2.0,2.0,1.0,2.0,2.0,5.0,NaN,NaN,NaN
2017-05,3596.0,18.0,18.0,14.0,11.0,12.0,15.0,6.0,9.0,11.0,9.0,12.0,9.0,1.0,7.0,9.0,NaN,NaN,NaN,NaN
2017-06,3139.0,15.0,11.0,13.0,8.0,12.0,12.0,7.0,4.0,7.0,10.0,11.0,5.0,4.0,6.0,NaN,NaN,NaN,NaN,NaN
2017-07,3894.0,20.0,14.0,10.0,11.0,8.0,12.0,4.0,7.0,10.0,9.0,12.0,5.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-08,4184.0,29.0,14.0,11.0,15.0,22.0,12.0,11.0,6.0,6.0,10.0,8.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-09,4130.0,28.0,22.0,12.0,19.0,9.0,9.0,10.0,12.0,7.0,11.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-10,4470.0,31.0,11.0,4.0,10.0,9.0,10.0,16.0,12.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11,7304.0,40.0,28.0,13.0,14.0,13.0,8.0,14.0,10.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-12,5487.0,14.0,15.0,19.0,15.0,11.0,9.0,3.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01,7025.0,24.0,27.0,20.0,20.0,11.0,12.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02,6451.0,25.0,25.0,19.0,17.0,14.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-03,6965.0,32.0,22.0,20.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04,6711.0,39.0,21.0,16.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-05,6622.0,35.0,18.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-06,5940.0,25.0,17.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-07,6071.0,44.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-08,6270.0,7.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-09,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
cohort_size = cohort_pivot.iloc[:, 0]

cohort_retention = cohort_pivot.divide(cohort_size, axis=0)
cohort_retention.round(3)

cohort_index,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19,20
cohort_month,,,,,,,,,,,,,,,,,,,,
2016-09,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-10,1.0,NaN,NaN,NaN,NaN,NaN,0.003,NaN,NaN,0.003,NaN,0.003,NaN,0.003,NaN,0.003,NaN,0.003,0.006,0.006
2016-12,1.0,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01,1.0,0.004,0.003,0.001,0.004,0.001,0.005,0.001,0.001,NaN,0.004,0.001,0.008,0.004,0.001,0.001,0.003,0.004,0.001,NaN
2017-02,1.0,0.002,0.003,0.001,0.004,0.001,0.002,0.002,0.002,0.002,0.001,0.003,0.002,0.002,0.001,0.001,0.001,0.002,NaN,NaN
2017-03,1.0,0.005,0.004,0.004,0.003,0.002,0.002,0.003,0.003,0.001,0.004,0.002,0.002,0.001,0.002,0.002,0.001,0.002,NaN,NaN
2017-04,1.0,0.006,0.002,0.002,0.003,0.003,0.003,0.003,0.003,0.002,0.003,0.001,0.001,0.000,0.001,0.001,0.002,NaN,NaN,NaN
2017-05,1.0,0.005,0.005,0.004,0.003,0.003,0.004,0.002,0.003,0.003,0.003,0.003,0.003,0.000,0.002,0.003,NaN,NaN,NaN,NaN
2017-06,1.0,0.005,0.004,0.004,0.003,0.004,0.004,0.002,0.001,0.002,0.003,0.004,0.002,0.001,0.002,NaN,NaN,NaN,NaN,NaN
2017-07,1.0,0.005,0.004,0.003,0.003,0.002,0.003,0.001,0.002,0.003,0.002,0.003,0.001,0.003,NaN,NaN,NaN,NaN,NaN,NaN
2017-08,1.0,0.007,0.003,0.003,0.004,0.005,0.003,0.003,0.001,0.001,0.002,0.002,0.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-09,1.0,0.007,0.005,0.003,0.005,0.002,0.002,0.002,0.003,0.002,0.003,0.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-10,1.0,0.007,0.002,0.001,0.002,0.002,0.002,0.004,0.003,0.002,0.002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11,1.0,0.005,0.004,0.002,0.002,0.002,0.001,0.002,0.001,0.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-12,1.0,0.003,0.003,0.003,0.003,0.002,0.002,0.001,0.002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01,1.0,0.003,0.004,0.003,0.003,0.002,0.002,0.002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02,1.0,0.004,0.004,0.003,0.003,0.002,0.002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-03,1.0,0.005,0.003,0.003,0.001,0.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04,1.0,0.006,0.003,0.002,0.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-05,1.0,0.005,0.003,0.002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-06,1.0,0.004,0.003,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-07,1.0,0.007,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-08,1.0,0.001,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-09,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df_customer_clv_final["total_orders"].describe()

count    96093.000000
mean         1.034800
std          0.214364
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         17.000000
Name: total_orders, dtype: float64

In [29]:
df_orders_revenue_clean["order_status"].value_counts()

order_status
delivered      96477
shipped         1107
canceled         622
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [30]:
df_orders_revenue_final = df_orders_revenue_clean[
    df_orders_revenue_clean["order_status"] == "delivered"
].copy()

df_orders_revenue_final["order_status"].value_counts()

order_status
delivered    96477
Name: count, dtype: int64

In [31]:
df_customer_clv_final = df_orders_revenue_final.groupby("customer_unique_id").agg(
    total_revenue=("payment_value", "sum"),
    total_orders=("order_id", "nunique"),
    first_purchase=("order_purchase_timestamp", "min"),
    last_purchase=("order_purchase_timestamp", "max")
).reset_index()

df_customer_clv_final.shape

(93357, 5)

In [32]:
df_customer_clv_final.shape

(93357, 5)

In [33]:
df_customer_clv_final["first_purchase"] = pd.to_datetime(
    df_customer_clv_final["first_purchase"]
)

df_customer_clv_final["cohort_month"] = (
    df_customer_clv_final["first_purchase"].dt.to_period("M")
)

df_customer_clv_final[["customer_unique_id", "cohort_month"]].head()

                 customer_unique_id cohort_month
0  0000366f3b9a7992bf8c76cfdf3221e2      2018-05
1  0000b849f77a49e4a4ce2b2a4ca5be3f      2018-05
2  0000f46a3911fa3c0805444483337064      2017-03
3  0000f6ccb0745a6a4b88665a16c9f078      2017-10
4  0004aac84e0df4da2b147fca70cf8255      2017-11

In [34]:
df_cohort = df_orders_revenue_final.merge(
    df_customer_clv_final[
        ["customer_unique_id", "cohort_month"]
    ],
    on="customer_unique_id",
    how="inner"
)

df_cohort.shape

(96477, 14)

In [35]:
df_cohort["order_purchase_timestamp"] = pd.to_datetime(
    df_cohort["order_purchase_timestamp"]
)

df_cohort["order_month"] = (
    df_cohort["order_purchase_timestamp"].dt.to_period("M")
)

df_cohort[["cohort_month", "order_month"]].head()

  cohort_month order_month
0      2017-09     2017-10
1      2018-07     2018-07
2      2018-08     2018-08
3      2017-11     2017-11
4      2018-02     2018-02

In [36]:
df_cohort["cohort_index"] = (
    (df_cohort["order_month"] - df_cohort["cohort_month"])
    .apply(lambda x: x.n)
)

df_cohort[["cohort_month", "order_month", "cohort_index"]].head()

  cohort_month order_month  cohort_index
0      2017-09     2017-10             1
1      2018-07     2018-07             0
2      2018-08     2018-08             0
3      2017-11     2017-11             0
4      2018-02     2018-02             0

In [37]:
cohort_pivot = df_cohort.pivot_table(
    index="cohort_month",
    columns="cohort_index",
    values="customer_unique_id",
    aggfunc="nunique"
)

cohort_pivot.head()

cohort_index,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19,20
cohort_month,,,,,,,,,,,,,,,,,,,,
2016-10,262.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,1.0,NaN,1.0,2.0,2.0
2016-12,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01,717.0,2.0,2.0,1.0,3.0,1.0,3.0,1.0,1.0,NaN,3.0,1.0,5.0,3.0,1.0,1.0,2.0,3.0,1.0,NaN
2017-02,1628.0,3.0,5.0,2.0,7.0,2.0,4.0,3.0,2.0,3.0,2.0,5.0,2.0,3.0,2.0,1.0,1.0,3.0,NaN,NaN
2017-03,2503.0,11.0,9.0,10.0,9.0,4.0,4.0,8.0,8.0,2.0,9.0,3.0,5.0,3.0,4.0,6.0,2.0,3.0,NaN,NaN

In [38]:
cohort_size = cohort_pivot.iloc[:, 0]

cohort_retention = cohort_pivot.divide(
    cohort_size,
    axis=0
)

cohort_retention.round(4)

cohort_index,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19,20
cohort_month,,,,,,,,,,,,,,,,,,,,
2016-10,1.0,NaN,NaN,NaN,NaN,NaN,0.0038,NaN,NaN,0.0038,NaN,0.0038,NaN,0.0038,NaN,0.0038,NaN,0.0038,0.0076,0.0076
2016-12,1.0,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01,1.0,0.0028,0.0028,0.0014,0.0042,0.0014,0.0042,0.0014,0.0014,NaN,0.0042,0.0014,0.0070,0.0042,0.0014,0.0014,0.0028,0.0042,0.0014,NaN
2017-02,1.0,0.0018,0.0031,0.0012,0.0043,0.0012,0.0025,0.0018,0.0012,0.0018,0.0012,0.0031,0.0012,0.0018,0.0012,0.0006,0.0006,0.0018,NaN,NaN
2017-03,1.0,0.0044,0.0036,0.0040,0.0036,0.0016,0.0016,0.0032,0.0032,0.0008,0.0036,0.0012,0.0020,0.0012,0.0016,0.0024,0.0008,0.0012,NaN,NaN
2017-04,1.0,0.0062,0.0022,0.0018,0.0027,0.0027,0.0035,0.0031,0.0031,0.0018,0.0027,0.0009,0.0004,0.0004,0.0009,0.0009,0.0013,NaN,NaN,NaN
2017-05,1.0,0.0046,0.0046,0.0029,0.0029,0.0032,0.0041,0.0014,0.0026,0.0026,0.0026,0.0035,0.0023,0.0003,0.0017,0.0020,NaN,NaN,NaN,NaN
2017-06,1.0,0.0049,0.0040,0.0043,0.0030,0.0040,0.0036,0.0023,0.0013,0.0020,0.0030,0.0036,0.0016,0.0016,0.0023,NaN,NaN,NaN,NaN,NaN
2017-07,1.0,0.0053,0.0035,0.0024,0.0029,0.0021,0.0032,0.0011,0.0019,0.0027,0.0021,0.0029,0.0013,0.0024,NaN,NaN,NaN,NaN,NaN,NaN
2017-08,1.0,0.0069,0.0035,0.0027,0.0035,0.0052,0.0030,0.0027,0.0015,0.0015,0.0025,0.0020,0.0012,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-09,1.0,0.0070,0.0055,0.0027,0.0045,0.0022,0.0022,0.0025,0.0027,0.0017,0.0025,0.0007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-10,1.0,0.0072,0.0025,0.0009,0.0023,0.0021,0.0021,0.0037,0.0028,0.0018,0.0021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11,1.0,0.0057,0.0037,0.0017,0.0017,0.0018,0.0011,0.0018,0.0013,0.0006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-12,1.0,0.0021,0.0028,0.0034,0.0026,0.0021,0.0017,0.0002,0.0019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01,1.0,0.0034,0.0037,0.0029,0.0029,0.0016,0.0018,0.0023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02,1.0,0.0035,0.0040,0.0030,0.0025,0.0022,0.0021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-03,1.0,0.0040,0.0030,0.0030,0.0012,0.0012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04,1.0,0.0059,0.0030,0.0024,0.0014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-05,1.0,0.0052,0.0026,0.0018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-06,1.0,0.0043,0.0027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-07,1.0,0.0052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-08,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
df_orders_revenue_final["order_purchase_timestamp"].max()

'2018-08-29 15:00:37'

In [41]:
df_orders_revenue_final["order_purchase_timestamp"] = pd.to_datetime(
    df_orders_revenue_final["order_purchase_timestamp"]
)

In [42]:
snapshot_date = (
    df_orders_revenue_final["order_purchase_timestamp"].max()
    + pd.Timedelta(days=1)
)

snapshot_date

Timestamp('2018-08-30 15:00:37')

In [43]:
rfm = df_orders_revenue_final.groupby("customer_unique_id").agg(
    Recency=("order_purchase_timestamp",
             lambda x: (snapshot_date - x.max()).days),

    Frequency=("order_id", "nunique"),

    Monetary=("payment_value", "sum")
).reset_index()

rfm.head()

                 customer_unique_id  Recency  Frequency  Monetary
0  0000366f3b9a7992bf8c76cfdf3221e2      112          1    141.90
1  0000b849f77a49e4a4ce2b2a4ca5be3f      115          1     27.19
2  0000f46a3911fa3c0805444483337064      537          1     86.22
3  0000f6ccb0745a6a4b88665a16c9f078      321          1     43.62
4  0004aac84e0df4da2b147fca70cf8255      288          1    196.89

In [44]:
rfm.describe()

            Recency     Frequency      Monetary
count  93357.000000  93357.000000  93357.000000
mean     237.936673      1.033420    165.198772
std      152.584315      0.209099    226.314579
min        1.000000      1.000000      9.590000
25%      114.000000      1.000000     63.060000
50%      219.000000      1.000000    107.780000
75%      346.000000      1.000000    182.560000
max      695.000000     15.000000  13664.080000

In [45]:
rfm["Frequency"].value_counts().sort_index()

Frequency
1     90556
2      2573
3       181
4        28
5         9
6         5
7         3
9         1
15        1
Name: count, dtype: int64

In [46]:
rfm["R_Score"] = pd.qcut(
    rfm["Recency"],
    5,
    labels=[5, 4, 3, 2, 1]
).astype(int)

rfm["R_Score"].value_counts().sort_index()

R_Score
1    18638
2    18577
3    18709
4    18705
5    18728
Name: count, dtype: int64

In [47]:
rfm["M_Score"] = pd.qcut(
    rfm["Monetary"],
    5,
    labels=[1, 2, 3, 4, 5]
).astype(int)

rfm["M_Score"].value_counts().sort_index()

M_Score
1    18673
2    18683
3    18658
4    18675
5    18668
Name: count, dtype: int64

In [48]:
rfm["F_Score"] = rfm["Frequency"].apply(
    lambda x: 1 if x == 1
    else 2 if x == 2
    else 3
)

rfm["F_Score"].value_counts().sort_index()

F_Score
1    90556
2     2573
3      228
Name: count, dtype: int64

In [49]:
rfm["RFM_Score"] = (
    rfm["R_Score"].astype(str) +
    rfm["F_Score"].astype(str) +
    rfm["M_Score"].astype(str)
)

rfm[
    ["customer_unique_id",
     "R_Score",
     "F_Score",
     "M_Score",
     "RFM_Score"]
].head()

                 customer_unique_id  R_Score  F_Score  M_Score RFM_Score
0  0000366f3b9a7992bf8c76cfdf3221e2        4        1        4       414
1  0000b849f77a49e4a4ce2b2a4ca5be3f        4        1        1       411
2  0000f46a3911fa3c0805444483337064        1        1        2       112
3  0000f6ccb0745a6a4b88665a16c9f078        2        1        1       211
4  0004aac84e0df4da2b147fca70cf8255        2        1        4       214

In [50]:
rfm["RFM_Score"].value_counts().head(20)

RFM_Score
212    3968
112    3905
311    3903
111    3880
414    3757
514    3742
413    3740
511    3709
314    3698
513    3693
313    3654
113    3628
312    3628
411    3609
213    3562
211    3545
412    3515
512    3512
115    3498
415    3497
Name: count, dtype: int64

In [51]:
def segment_customer(row):

    if row["F_Score"] >= 2 and row["R_Score"] >= 4:
        return "Champions"

    elif row["F_Score"] >= 2:
        return "Loyal Customers"

    elif row["R_Score"] >= 4 and row["M_Score"] >= 4:
        return "High Value New"

    elif row["R_Score"] <= 2:
        return "At Risk"

    else:
        return "Regular Customers"


rfm["Segment"] = rfm.apply(segment_customer, axis=1)

rfm["Segment"].value_counts()

Segment
Regular Customers    39883
At Risk              36227
High Value New       14446
Loyal Customers       1592
Champions             1209
Name: count, dtype: int64

In [52]:
rfm.groupby("Segment").agg({
    "Recency": "mean",
    "Frequency": "mean",
    "Monetary": "mean"
}).round(2)

                   Recency  Frequency  Monetary
Segment
At Risk             395.34       1.00    161.90
Champions            89.16       2.15    322.23
High Value New       91.60       1.00    302.14
Loyal Customers     319.88       2.08    298.23
Regular Customers   149.21       1.00    108.53

In [53]:
segment_summary = rfm.groupby("Segment").agg(
    Customers=("customer_unique_id", "count"),
    Avg_Recency=("Recency", "mean"),
    Avg_Frequency=("Frequency", "mean"),
    Avg_Monetary=("Monetary", "mean"),
    Total_Revenue=("Monetary", "sum")
).round(2)

segment_summary

,Customers,Avg_Recency,Avg_Frequency,Avg_Monetary,Total_Revenue
Segment,,,,,
At Risk,36227,395.34,1.00,161.90,5865102.23
Champions,1209,89.16,2.15,322.23,389570.36
High Value New,14446,91.60,1.00,302.14,4364648.55
Loyal Customers,1592,319.88,2.08,298.23,474786.85
Regular Customers,39883,149.21,1.00,108.53,4328353.78

In [54]:
segment_summary["Revenue_%"] = (
    segment_summary["Total_Revenue"]
    / segment_summary["Total_Revenue"].sum()
    * 100
).round(2)

segment_summary.sort_values(
    "Revenue_%",
    ascending=False
)

,Customers,Avg_Recency,Avg_Frequency,Avg_Monetary,Total_Revenue,Revenue_%
Segment,,,,,,
At Risk,36227,395.34,1.00,161.90,5865102.23,38.03
High Value New,14446,91.60,1.00,302.14,4364648.55,28.30
Regular Customers,39883,149.21,1.00,108.53,4328353.78,28.07
Loyal Customers,1592,319.88,2.08,298.23,474786.85,3.08
Champions,1209,89.16,2.15,322.23,389570.36,2.53

In [55]:
segment_summary["Customer_%"] = (
    segment_summary["Customers"]
    / segment_summary["Customers"].sum()
    * 100
).round(2)

segment_summary.sort_values(
    "Customer_%",
    ascending=False
)

,Customers,Avg_Recency,Avg_Frequency,Avg_Monetary,Total_Revenue,Revenue_%,Customer_%
Segment,,,,,,,
Regular Customers,39883,149.21,1.00,108.53,4328353.78,28.07,42.72
At Risk,36227,395.34,1.00,161.90,5865102.23,38.03,38.80
High Value New,14446,91.60,1.00,302.14,4364648.55,28.30,15.47
Loyal Customers,1592,319.88,2.08,298.23,474786.85,3.08,1.71
Champions,1209,89.16,2.15,322.23,389570.36,2.53,1.30

In [56]:
rfm.to_csv("rfm_customer_segments.csv", index=False)

In [57]:
df_orders_revenue_final.to_csv(
    "orders_final.csv",
    index=False
)